# Generated by Django 3.2.2 on 2021-06-05 18:51

from django.db import migrations


def add_predefined_choices(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    StakeholderGroup = apps.get_model("api", "StakeholderGroup")
    SupportSource = apps.get_model("api", "SupportSource")

    StakeholderGroup.objects.using(db_alias).bulk_create([
        StakeholderGroup(name="local community"),
        StakeholderGroup(name="user group"),
        StakeholderGroup(name="NGO"),
        StakeholderGroup(name="academic"),
        StakeholderGroup(name="government"),
        StakeholderGroup(name="private sector"),
        StakeholderGroup(name="indigenous peoples"),
    ])

    SupportSource.objects.using(db_alias).bulk_create([
        SupportSource(name="conservation NGOs"),
        SupportSource(name="other NGOs"),
        SupportSource(name="international organizations"),
        SupportSource(name="national government"),
        SupportSource(name="provincial government"),
        SupportSource(name="local government"),
        SupportSource(name="academia (university)"),
        SupportSource(name="private sector"),
    ])


def remove_predefined_choices(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    StakeholderGroup = apps.get_model("api", "StakeholderGroup")
    SupportSource = apps.get_model("api", "SupportSource")

    StakeholderGroup.objects.using(db_alias).filter(name="local community").delete()
    StakeholderGroup.objects.using(db_alias).filter(name="user group").delete()
    StakeholderGroup.objects.using(db_alias).filter(name="NGO").delete()
    StakeholderGroup.objects.using(db_alias).filter(name="academic").delete()
    StakeholderGroup.objects.using(db_alias).filter(name="government").delete()
    StakeholderGroup.objects.using(db_alias).filter(name="private sector").delete()
    StakeholderGroup.objects.using(db_alias).filter(name="indigenous peoples").delete()

    SupportSource.objects.using(db_alias).filter(name="conservation NGOs").delete()
    SupportSource.objects.using(db_alias).filter(name="other NGOs").delete()
    SupportSource.objects.using(db_alias).filter(name="international organizations").delete()
    SupportSource.objects.using(db_alias).filter(name="national government").delete()
    SupportSource.objects.using(db_alias).filter(name="provincial government").delete()
    SupportSource.objects.using(db_alias).filter(name="local government").delete()
    SupportSource.objects.using(db_alias).filter(name="academia (university)").delete()
    SupportSource.objects.using(db_alias).filter(name="private sector").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_predefined_choices, remove_predefined_choices)
    ]
