# Generated by Django 3.2.2 on 2021-05-10 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('count_manager', models.PositiveSmallIntegerField(default=0, verbose_name='MA manager count')),
                ('count_personnel', models.PositiveSmallIntegerField(default=0, verbose_name='MA personnel count')),
                ('count_government', models.PositiveSmallIntegerField(default=0, verbose_name='government personnel count')),
                ('count_committee', models.PositiveSmallIntegerField(default=0, verbose_name='local community/indigenous committee count')),
                ('count_community', models.PositiveSmallIntegerField(default=0, verbose_name='community leader count')),
                ('focal_area', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_created_by', to=settings.AUTH_USER_MODEL)),
                ('management_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ma_assessments', to='api.managementarea')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
