# Generated by Django 3.2.2 on 2021-09-04 14:39

import django.contrib.postgres.fields
from django.db import migrations, models


varchar_to_array_sql = """
ALTER TABLE api_managementarea 
	ALTER recognition_level DROP DEFAULT,
	ALTER recognition_level TYPE TEXT[] USING ARRAY[recognition_level],
	ALTER recognition_level SET DEFAULT '{}';
UPDATE api_managementarea
	SET recognition_level = '{}' WHERE recognition_level = '{NULL}';
"""

reverse_sql = """
ALTER TABLE api_managementarea
	ALTER recognition_level TYPE TEXT;
"""


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            varchar_to_array_sql,
            reverse_sql,
            state_operations=[
                migrations.AlterField(
                    model_name='managementarea',
                    name='recognition_level',
                    field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(
                        choices=[('local', 'local'), ('national', 'national'), ('international', 'international')]
                    ), blank=True, default=list, size=None),
                    preserve_default=False,
                ),
            ]
        ),
        migrations.AddField(
            model_name='managementarea',
            name='containedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='mas_inside', to='api.managementarea'),
        ),
        migrations.AlterField(
            model_name='managementarea',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='versions', to='api.managementarea'),
        ),
    ]
