# Generated by Django 3.2.2 on 2021-06-11 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0002_auto_20210605_1851"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagementAreaZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "access_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (90, "Open access (open for extraction and entering)"),
                            (50, "Fully restricted access (total extraction ban)"),
                            (
                                10,
                                "Partially Restricted (e.g., periodic closures, restriction by use type, restriction by activity type, species restrictions, gear restrictions, etc.)",
                            ),
                        ],
                        default=90,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managementareazone_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "management_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ma_zones",
                        to="api.managementareaversion",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managementareazone_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "management area zone",
            },
        ),
        migrations.RemoveField(
            model_name="managementareaversion",
            name="access_level",
        ),
        migrations.RemoveField(
            model_name="managementareaversion",
            name="access_level_description",
        ),
    ]
