# Generated by Django 3.2.2 on 2021-09-10 16:49

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ma_recognition_level_add_ma_containedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementarea',
            name='countries',
            field=django_countries.fields.CountryField(blank=True, max_length=746, multiple=True),
        ),
    ]
