# Generated by Django 3.2.2 on 2021-05-23 03:03

from django.db import migrations


def createfirstmagroup(apps, schema_editor):
    ManagementAreaGroup = apps.get_model("api", "ManagementAreaGroup")
    ManagementAreaGroup.objects.create()


def removefirstmagroup(apps, schema_editor):
    ManagementAreaGroup = apps.get_model("api", "ManagementAreaGroup")
    ManagementAreaGroup.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_managementareagroup'),
    ]

    operations = [
        migrations.RunPython(createfirstmagroup, removefirstmagroup)
    ]
