# Generated by Django 4.2.23 on 2025-11-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_assessment_collection_method_text_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='collection_method_text_mg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='context_mg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='name_mg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='needs_explanation_mg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='strengths_explanation_mg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentversion',
            name='text_mg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='description_mg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_mg',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='description_mg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='name_mg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='governancetype',
            name='name_mg',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='managementarea',
            name='geospatial_sources_mg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementarea',
            name='name_mg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='managementarea',
            name='objectives_mg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementareazone',
            name='description_mg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementareazone',
            name='name_mg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='managementauthority',
            name='name_mg',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_mg',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='protectedarea',
            name='name_mg',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_mg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stakeholdergroup',
            name='name_mg',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supportsource',
            name='name_mg',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='surveyanswerlikert',
            name='explanation_mg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='average_1_mg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='excellent_3_mg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='good_2_mg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='guidance_mg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='information_mg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='poor_0_mg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='rationale_mg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='text_mg',
            field=models.TextField(null=True),
        ),
    ]
