# Generated by Django 3.2.2 on 2021-05-23 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210523_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementarea',
            name='management_area_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.managementareagroup'),
            preserve_default=False,
        ),
    ]
