# Generated by Django 3.2.2 on 2021-06-13 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_managementareazone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="managementareaversion",
            old_name="authority_name",
            new_name="management_authority",
        ),
        migrations.RenameField(
            model_name="managementareazone",
            old_name="management_area",
            new_name="management_area_version",
        ),
    ]
