# Generated by Django 3.2.2 on 2021-10-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210922_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='count_committee',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='count_manager',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='count_personnel',
        ),
        migrations.AddField(
            model_name='assessment',
            name='collection_method',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Through knowledge of the person(s) responsible for filling out assessment'), (20, 'Through knowledge of the person(s) responsible for filling our assessment  and acquired external input from informal conversations and secondary documents'), (30, 'Through semi-structured interviews and focus group')], null=True, verbose_name='Please choose which option best describes how information for this assessment was collected'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='collection_method_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='count_academic',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='academic personnel count'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='count_indigenous',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='indigenous leader count'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='count_ngo',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='NGO personnel count'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='count_private',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='private sector personnel count'),
        ),
        migrations.AddField(
            model_name='managementarea',
            name='objectives',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='count_community',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='local community leader count'),
        ),
    ]
