# Generated by Django 3.2.2 on 2021-08-15 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "api",
            "0004_rename_authority_name_managementareaversion_management_authority",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="region",
            options={},
        ),
        migrations.AlterField(
            model_name="governancetype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="managementauthority",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="protectedarea",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="stakeholdergroup",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="supportsource",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="region",
            unique_together={("name", "country")},
        ),
        migrations.AlterField(
            model_name="assessment",
            name="management_area_version",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ma_assessments",
                to="api.managementareaversion",
            ),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name="assessment",
            options={"ordering": ["name", "year"]},
        ),
        migrations.AlterUniqueTogether(
            name="collaborator",
            unique_together={("assessment", "user")},
        ),
    ]
