# Generated by Django 3.2.2 on 2021-10-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211002_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='person_responsible_role_other',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
