# Generated by Django 3.2.2 on 2021-08-26 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210819_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementareaversion',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='managementareaversion',
            name='version_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
