# Generated by Django 3.2.5 on 2021-10-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_assessment_person_responsible_role_other'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='monitoring_used_text',
            new_name='ecological_monitoring_used_text',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='climatechange_assessed',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='climatechange_assessed_text',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='monitoring_used',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='multiple_knowledge_ecological',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='multiple_knowledge_ecological_text',
        ),
        migrations.AddField(
            model_name='assessment',
            name='ecological_monitoring_used',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, "don't know [10]"), (20, 'poor [20]'), (30, 'average [30]'), (40, 'good [40]'), (50, 'excellent [50]')], null=True, verbose_name='Are systems in place to monitor and document ecological conditions in the MA?'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='social_monitoring_used',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, "don't know [10]"), (20, 'poor [20]'), (30, 'average [30]'), (40, 'good [40]'), (50, 'excellent [50]')], null=True, verbose_name='Are systems in place to monitor and document the social conditions of communities in and/or adjacent to the MA?'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='social_monitoring_used_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='collection_method',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Through knowledge of the person(s) responsible for filling out assessment'), (20, 'Through knowledge of the person(s) responsible for filling our assessment  and acquired external input from informal conversations and secondary documents'), (30, 'Through semi-structured interviews and/or focus groups')], null=True, verbose_name='Please choose which option best describes how information for this assessment was collected'),
        ),
    ]
