# Generated by Django 3.2.5 on 2021-11-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211020_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='consent_given_written',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='collection_method',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Through knowledge of the person(s) responsible for filling out assessment'), (20, 'Through knowledge of the person(s) responsible for filling our assessment  and acquired external input from informal conversations and secondary documents'), (30, 'Through semi-structured interviews and/or focus groups'), (40, 'A combination of the above'), (50, 'Other (please provide details below)')], null=True, verbose_name='Please choose which option best describes how information for this assessment was collected'),
        ),
    ]
