# Generated by Django 3.2.13 on 2022-06-05 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220602_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyanswerlikert',
            options={'ordering': ['assessment', 'question'], 'verbose_name': 'Likert survey answer'},
        ),
        migrations.AlterModelOptions(
            name='surveyquestionlikert',
            options={'ordering': ['number'], 'verbose_name': 'Likert survey question'},
        ),
        migrations.AlterUniqueTogether(
            name='surveyanswerlikert',
            unique_together={('assessment', 'question')},
        ),
    ]
