# Generated by Django 3.2.13 on 2022-06-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220605_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyanswerlikert',
            options={'verbose_name': 'Likert survey answer'},
        ),
        migrations.AlterField(
            model_name='assessment',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='api.Attribute'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
