# Generated by Django 3.2.13 on 2022-07-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestionlikert',
            name='number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterModelOptions(
            name='surveyquestionlikert',
            options={'ordering': ['attribute', 'number'], 'verbose_name': 'Likert survey question'},
        ),
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(90, 'not finalized'), (80, 'test'), (10, 'finalized')], default=90),
        ),
        migrations.AddField(
            model_name='attribute',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
