# Generated by Django 3.2.13 on 2022-08-08 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0015_auto_20220804_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datetime_resolved', models.DateTimeField(blank=True, null=True)),
                ('flag_type', models.CharField(blank=True, choices=[('inappropriate', 'inappropriate language or content'), ('personal', 'personal information'), ('inaccurate', 'inaccurate details')], max_length=20)),
                ('flag_type_other', models.CharField(blank=True, max_length=255)),
                ('explanation', models.TextField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_flags', to='api.assessment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessmentflag_created_by', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assessment_flags', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessmentflag_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on', 'assessment', 'reporter__username'],
            },
        ),
    ]
