# Generated by Django 3.2.13 on 2022-08-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20220809_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='collection_method',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Desk-based assessment'), (30, 'Field-based assessment'), (50, 'Other (please provide details below)')], null=True, verbose_name='Please choose which option best describes how information for this assessment was collected'),
        ),
    ]
