# Generated by Django 3.2.15 on 2022-10-17 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_assessment_collection_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyanswerlikert',
            options={'ordering': ['question__attribute__order', 'question__number'], 'verbose_name': 'Likert survey answer'},
        ),
        migrations.AlterField(
            model_name='assessment',
            name='data_policy',
            field=models.PositiveSmallIntegerField(choices=[(10, 'private'), (90, 'public')], default=10),
        ),
        migrations.AlterField(
            model_name='surveyanswerlikert',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_answer_likerts', to='api.assessment'),
        ),
    ]
