# Generated by Django 3.2.15 on 2022-10-27 13:33

import api.models.base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20221017_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='assessment',
            name='collection_method_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='collection_method_text_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='collection_method_text_ind',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='collection_method_text_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='name_ind',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='name_sw',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assessmentversion',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentversion',
            name='text_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentversion',
            name='text_ind',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentversion',
            name='text_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='description_ind',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='description_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_es',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_ind',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_sw',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='description_ind',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='description_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='name_ind',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='name_sw',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='version',
            field=models.ForeignKey(default=api.models.base.latest_version, on_delete=django.db.models.deletion.PROTECT,
                                    to='api.assessmentversion'),
        ),
        migrations.AddField(
            model_name='governancetype',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='governancetype',
            name='name_es',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='governancetype',
            name='name_ind',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='governancetype',
            name='name_sw',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='managementarea',
            name='geospatial_sources_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementarea',
            name='geospatial_sources_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementarea',
            name='geospatial_sources_ind',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementarea',
            name='geospatial_sources_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementarea',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='managementarea',
            name='name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='managementarea',
            name='name_ind',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='managementarea',
            name='name_sw',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='managementarea',
            name='objectives_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementarea',
            name='objectives_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementarea',
            name='objectives_ind',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementarea',
            name='objectives_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementareazone',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementareazone',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementareazone',
            name='description_ind',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementareazone',
            name='description_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementareazone',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='managementareazone',
            name='name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='managementareazone',
            name='name_ind',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='managementareazone',
            name='name_sw',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='managementauthority',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='managementauthority',
            name='name_es',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='managementauthority',
            name='name_ind',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='managementauthority',
            name='name_sw',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_es',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_ind',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_sw',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='protectedarea',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='protectedarea',
            name='name_es',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='protectedarea',
            name='name_ind',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='protectedarea',
            name='name_sw',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_ind',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_sw',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stakeholdergroup',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stakeholdergroup',
            name='name_es',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stakeholdergroup',
            name='name_ind',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stakeholdergroup',
            name='name_sw',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supportsource',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supportsource',
            name='name_es',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supportsource',
            name='name_ind',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supportsource',
            name='name_sw',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='surveyanswerlikert',
            name='explanation_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyanswerlikert',
            name='explanation_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyanswerlikert',
            name='explanation_ind',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyanswerlikert',
            name='explanation_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='average_30_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='average_30_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='average_30_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='average_30_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='dontknow_10_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='dontknow_10_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='dontknow_10_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='dontknow_10_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='excellent_50_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='excellent_50_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='excellent_50_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='excellent_50_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='good_40_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='good_40_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='good_40_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='good_40_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='poor_20_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='poor_20_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='poor_20_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='poor_20_sw',
            field=models.TextField(null=True),
        ),
    ]
