# Generated by Django 3.2.15 on 2022-11-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20221027_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='guidance_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='guidance_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='guidance_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='guidance_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='information_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='information_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='information_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='information_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='rationale_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='rationale_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='rationale_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='rationale_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='text_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='text_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='text_sw',
            field=models.TextField(null=True),
        ),
    ]
