# Generated by Django 3.2.15 on 2022-11-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20221116_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='count_gender_female',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='female count'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='count_gender_male',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='male count'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='count_gender_nonbinary',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='non-binary count'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='count_gender_prefer_not_say',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='prefer not to declare gender count'),
        ),
    ]
