# Generated by Django 3.2.18 on 2023-04-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20221116_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyanswerlikert',
            name='choice',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, "don't know [10]"), (20, 'poor [20]'), (30, 'average [30]'), (40, 'good [40]'), (50, 'excellent [50]')], null=True),
        ),
    ]
