# Generated by Django 3.2.18 on 2023-04-29 21:16

from django.db import migrations


DONTKNOW = 10
POOR = 20
AVERAGE = 30
GOOD = 40
EXCELLENT = 50


def migrate_scores(apps, schema_editor):
    SurveyAnswerLikert = apps.get_model("api", "SurveyAnswerLikert")
    for answer in SurveyAnswerLikert.objects.all():
        existing_choice = answer.choice
        new_choice = None
        if existing_choice == POOR:
            new_choice = 0
        if existing_choice == AVERAGE:
            new_choice = 1
        if existing_choice == GOOD:
            new_choice = 2
        if existing_choice == EXCELLENT:
            new_choice = 3

        answer.choice = new_choice
        answer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_surveyanswerlikert_choice'),
    ]

    operations = [
        migrations.RunPython(migrate_scores, migrations.RunPython.noop)
    ]
