# Generated by Django 3.2.18 on 2023-05-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20230429_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='context',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='context_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='context_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='context_ind',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='context_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='needs_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='needs_explanation_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='needs_explanation_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='needs_explanation_ind',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='needs_explanation_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='strengths_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='strengths_explanation_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='strengths_explanation_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='strengths_explanation_ind',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='strengths_explanation_sw',
            field=models.TextField(blank=True, null=True),
        ),
    ]
