# Generated by Django 3.2.20 on 2023-10-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_activelanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='collection_method_text_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='context_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='name_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='needs_explanation_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='strengths_explanation_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentversion',
            name='text_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='description_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_pt',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='description_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='name_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='governancetype',
            name='name_pt',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='managementarea',
            name='geospatial_sources_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementarea',
            name='name_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='managementarea',
            name='objectives_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementareazone',
            name='description_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementareazone',
            name='name_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='managementauthority',
            name='name_pt',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_pt',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='protectedarea',
            name='name_pt',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stakeholdergroup',
            name='name_pt',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supportsource',
            name='name_pt',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='surveyanswerlikert',
            name='explanation_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='average_1_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='excellent_3_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='good_2_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='guidance_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='information_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='poor_0_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='rationale_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionlikert',
            name='text_pt',
            field=models.TextField(null=True),
        ),
    ]
