name: Deploy app to AWS Elastic Beanstalk

on:
  push:
    branches:
      - dev
    tags:
      - v[0-9]+.[0-9]+.[0-9]+  # v1.2.3

jobs:
  build_and_push:
    name: Build Docker image and push to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=auto
          # list of Docker images to use as base name for tags
          images: |
            WWFGlobalScience/elinor-api
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha
            type=semver,pattern={{version}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
